# Generated by Django 4.0.6 on 2022-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_image_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
