# Generated by Django 4.0.6 on 2022-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_topic_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
