# Generated by Django 4.0.6 on 2022-07-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_topic_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
