# Generated by Django 4.0.6 on 2022-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
